# Generated by Django 4.2 on 2023-04-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_alter_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='author',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
