# Generated by Django 4.2 on 2023-04-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogPost',
            new_name='blog_post',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='author',
            new_name='subscribers',
        ),
    ]
