# Generated by Django 4.2 on 2023-04-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_rename_blogpost_comment_blog_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Not selected'), (2, 'Sport'), (3, 'Fishing'), (4, 'Tourism'), (5, 'Other')], default=1),
        ),
    ]
