# Generated by Django 4.2 on 2023-04-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_topic_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='genre',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.IntegerField(choices=[(1, 'Not selected'), (2, 'Sport'), (3, 'Fishing'), (4, 'Tourism'), (5, 'Other')], default=1),
        ),
    ]
